export const BTN_ACTIONS = {
    ADD:"ADD",
    DELETE:"DELETE",
    THEME:"THEME",
    CALC:"CALC"
}

export const btnData =[
    {
        display:"C",
        action:BTN_ACTIONS.DELETE,
        class:"btn__operator"
    },
    {
        display:"(",
        action:BTN_ACTIONS.ADD,
        class:"btn__operator"
    },
    {
        display:")",
        action:BTN_ACTIONS.ADD,
        class:"btn__operator"
    },
    {
        display:"/",
        action:BTN_ACTIONS.ADD,
        class:"btn__operator"
    },
    {
        display:"7",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"8",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"9",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"x",
        action:BTN_ACTIONS.ADD,
        class:"btn__operator"
    },
    {
        display:"4",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"5",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"6",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"+",
        action:BTN_ACTIONS.ADD,
        class:"btn__operator"
    },
    {
        display:"1",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"2",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"3",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"+",
        action:BTN_ACTIONS.ADD,
        class:"btn__operator"
    },
    {
        display:"D/L",
        action:BTN_ACTIONS.THEME,
        class:"btn__number"
    },
    {
        display:"0",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:".",
        action:BTN_ACTIONS.ADD,
        class:"btn__number"
    },
    {
        display:"=",
        action:BTN_ACTIONS.CALC,
        class:"btn__result"
    },
]